services:
  db:
    env_file:
      - ../backend/.env
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
      args:
        USER_ID: ${USER_ID}
    networks:
      - default
    volumes:
      - ../backend:/app/
      - composer_cache:/home/dev/.composer
      - ./backend/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=172.17.0.1

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on: [backend]
    links:
      - backend
    networks:
      - default
      - nginx
    volumes:
      - ../backend:/app/
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: ${BASE_DOMAIN}
      VIRTUAL_PATH: ~^/(admin|css/filament|css/solution-forest|js/filament|livewire|js/solution-forest|js/amidesfahani|css/amidesfahani|api|storage|telescope|vendor/telescope)

  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.4.0
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
    networks:
      - default
      - nginx
    environment:
      HTTPS_METHOD: redirect
      CONFIG: ""
    volumes:
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  docs:
    image: swaggerapi/swagger-ui:v5.17.14
    networks:
      - default
      - nginx
    environment:
      SWAGGER_JSON_URL: /docs/openapi.yaml
      BASE_URL: /docs
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${BASE_DOMAIN}
      VIRTUAL_PATH: /docs
    volumes:
      - ../backend/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

#  frontend:

volumes:
  db:
  composer_cache:
  vhost:
  conf:
  html:
  certs:
  data:

networks:
  nginx:
    name: nginx
    driver: bridge